# REDCap factoring script, labelling only, ff_label() instead of Hmisc.
# https://surgicalinformatics.github.io/cookbook/redcap.html#applying-a-redcap-factoring-script
# in addition, leading and trailing spaces in some label names removed.
library(finalfit)
library(magrittr)
library(forcats)


data = data %>% 
  # remove subvariable labels (in {var})
  mutate(across(where(is_character), ~str_remove_all(., " \\s*\\{[^\\)]+\\}"))) %>% 
  # remove HTML tags
  mutate(across(where(is_character), ~str_remove_all(., "<b>|</b>")))



data %>% 
  count(postop30_comp_leak)


# remove: 
# replace   %<>% fct_relevel( with  %<>% fct_relevel(
# remove 
data$period %<>% fct_relevel("Period 1: 31st Jul - 13th Aug 2023","Period 2: 14th Aug - 27th Aug 2023","Period 3: 28th Aug - 10th Sept 2023","Period 4: 11th Sept - 24th Sept 2023","Period 5: 25th Sept - 8th Oct 2023","Period 6: 9th Oct - 22nd Oct 2023","Period 7: 23rd Oct - 5th Nov 2023","Period 8: 6th Nov - 19th Nov 2023")
data$op_approach %<>% fct_relevel("Open","Open conversion","Laparoscopic","Robotic")
data$op_approach_mis_type %<>% fct_relevel("Standard","Single Incision Laparoscopic Surgery (SILS)")
data$op_performed %<>% fct_relevel("Total cholecystectomy","Subtotal cholecystectomy","Not performed")
data$gender %<>% fct_relevel("Female","Male")
data$asa  %<>% fct_relevel("I (normal healthy patient)","II (mild systemic disease without significant functional limitation)","III (severe systemic disease with significant functional limitation)","IV (severe systemic disease with constant threat to life)","V (critically ill patient not expected to survive without the operation)","Unknown")
data$bmi  %<>% fct_relevel("Underweight BMI Below 18.5","Normal weight BMI 18.5-24.9","Pre-obesity BMI 25.0-29.9","Obesity class I BMI 30.0-34.9","Obesity class II BMI 35.0-39.9","Obesity class III BMI 40+","Unknown")
data$frailty  %<>% fct_relevel("1 (Very fit)","2 (Well)","3 (Managing well)","4 (Vulnerable)","5 (Mildly frail)","6 (Moderately frail)","7 (Severely frail)","8 (Very severely frail)","9 (Terminally ill)","Unknown")
data$pt_comorbid_dm  %<>% fct_relevel("Diet-Controlled","Medication (non-insulin) controlled","Insulin-controlled","Unknown")
data$pt_comorbid_tumour  %<>% fct_relevel("Localised","Metastatic","Unknown")
data$pt_comorbid_liver  %<>% fct_relevel("Mild","Moderate to Severe","Unknown")
data$pt_comorbid_ckd  %<>% fct_relevel("Stage I","Stage II","Stage IIIa","Stage IIIb","Stage IV","Stage V","Unknown")
data$hist_ac  %<>% fct_relevel("Yes","No")
data$pre_img_us  %<>% fct_relevel("Yes","No (Not available)","No (Not indicated)","No (Patient declined)","Unknown")
data$pre_img_ct  %<>% fct_relevel("Yes","No (Not available)","No (Not indicated)","No (Patient declined)","Unknown")
data$pre_img_mrcp  %<>% fct_relevel("Yes","No (Not available)","No (Not indicated)","No (Patient declined)","Unknown")
data$pre_img_ercp  %<>% fct_relevel("Yes","No (Not available)","No (Not indicated)","No (Patient declined)","Unknown")
data$pre_img_eus  %<>% fct_relevel("Yes","No (Not available)","No (Not indicated)","No (Patient declined)","Unknown")
data$pre_img_hida  %<>% fct_relevel("Yes","No (Not available)","No (Not indicated)","No (Patient declined)","Unknown")
data$pre_urgency  %<>% fct_relevel("Elective","Delayed","Emergency")
data$pre_indication  %<>% fct_relevel("Acute calculous cholecystitis","Biliary colic","Acalculous cholecystitis","Chronic calculous cholecystitis","Common Bile Duct (CBD) stone","Gallbladder polyp","Dyskinesia","Gallstone pancreatitis")
data$pre_indication_tg  %<>% fct_relevel("I","II","III")
data$pre_indication_atlanta  %<>% fct_relevel("Mild","Moderate","Severe")
data$op_abx_yn  %<>% fct_relevel("No","Yes","Unknown")
data$op_operator  %<>% fct_relevel("Consultant or attending","Senior trainee (i.e., senior registrar or resident with >4 years surgical training/residency)","Junior trainee (i.e., junior registrar or resident with ≤ 4 years surgical training/residency)","Non-surgeon (e.g., medical practitioner or nurse)")
data$op_operator_cons  %<>% fct_relevel("General","Oesophago-gastric (OG)","HPB","Colorectal","Breast","Vascular","Other")
data$op_approach_mis_reuse  %<>% fct_relevel("No","Yes","Unknown")
data$op_nassar  %<>% fct_relevel("I","II","III","IV","V","Unknown")
data$op_cvs_yn  %<>% fct_relevel("Yes (CVS documented as obtained)","No (CVS documented as not obtained)","CVS not documented")
data$op_drain_yn  %<>% fct_relevel("No","Yes")
data$op_biliary_var  %<>% fct_relevel("No","Yes","Unknown")
data$op_cbd_explore  %<>% fct_relevel("Yes (Trancystic)","Yes (Choledochotomy)","No")
data$op_cbd_explore_close  %<>% fct_relevel("Primary closure","T-tube")
data$op_contam  %<>% fct_relevel("Clean (Gastrointestinal (GI) and genitourinary (GU) tract not entered)","Clean-Contaminated (GI or GU tracts entered but no gross contamination)","Contaminated (GI or GU tracts entered with gross spillage or major break in sterile technique)","Dirty (There is already contamination prior to operation, e.g., faeces or bile).")
data$op_reuse_gown  %<>% fct_relevel("No","Yes","Unknown")
data$op_reuse_drape  %<>% fct_relevel("No","Yes","Unknown")
data$postop30_cd  %<>% fct_relevel("0 (no complications)","I","II","IIIa","IIIb","IVa","IVb","V (death)")
data$postop30_cc_yn  %<>% fct_relevel("Yes","No")
data$postop30_reimg  %<>% fct_relevel("No","Yes")
data$postop30_comp_ssi  %<>% fct_relevel("0 (no complication)","I","II","IIIa","IIIb","IVa","IVb","V (death)")
data$postop30_comp_ppc  %<>% fct_expand("0 (no complication)","I","II","IIIa","IIIb","IVa","IVb","V (death)")
data$postop30_comp_ppc  %<>% fct_relevel("0 (no complication)","I","II","IIIa","IIIb","IVa","IVb","V (death)")
data$postop30_comp_leak  %<>% fct_expand("0 (no complication)","I","II","IIIa","IIIb","IVa","IVb","V (death)")
data$postop30_comp_leak  %<>% fct_relevel("0 (no complication)","I","II","IIIa","IIIb","IVa","IVb","V (death)")
data$postop30_comp_collec  %<>% fct_expand("0 (no complication)","I","II","IIIa","IIIb","IVa","IVb","V (death)")
data$postop30_comp_collec  %<>% fct_relevel("0 (no complication)","I","II","IIIa","IIIb","IVa","IVb","V (death)")
data$postop30_comp_ap  %<>% fct_expand("0 (no complication)","I","II","IIIa","IIIb","IVa","IVb","V (death)")
data$postop30_comp_ap  %<>% fct_relevel("0 (no complication)","I","II","IIIa","IIIb","IVa","IVb","V (death)")
data$postop30_readm  %<>% fct_relevel("Yes","No")
data$bdi_yn  %<>% fct_relevel("Yes","No")
data$hist_exam_yn  %<>% fct_relevel("Yes, sent for examination","No, not sent for examination")
data$postop30_cd_drain  %<>% fct_relevel("Yes","No")
data$postop30_cd_reop  %<>% fct_relevel("Yes","No")
data$postop30_comp_bleed  %<>% fct_expand("0 (no complication)","I","II","IIIa","IIIb","IVa","IVb","V (death)")
data$postop30_comp_bleed  %<>% fct_relevel("0 (no complication)","I","II","IIIa","IIIb","IVa","IVb","V (death)")


data$record_id %<>% ff_label("Record ID")
data$redcap_data_access_group %<>% ff_label("Data Access Group")
data$period %<>% ff_label("Data collection period")
data$op_approach %<>% ff_label("Operative approach")
data$op_approach_mis_type %<>% ff_label("Minimally invasive (laparoscopic or robotic) technique")
data$op_performed %<>% ff_label("Operation performed")
data$age_years %<>% ff_label("Age")
data$gender %<>% ff_label("Sex at birth")
data$asa %<>% ff_label("ASA grade (ASA grade descriptions found here)")
data$bmi %<>% ff_label("Body Mass Index (BMI)")
data$frailty %<>% ff_label("Clinical Frailty Scale")
data$pt_comorbid %<>% ff_label("Comorbidities Tick all that apply")
data$pt_comorbid_dm %<>% ff_label("Diabetes")
data$pt_comorbid_tumour %<>% ff_label("Solid Tumour")
data$pt_comorbid_liver %<>% ff_label("Liver disease")
data$pt_comorbid_ckd %<>% ff_label("Chronic Kidney Disease")
data$hist_ac %<>% ff_label("History of acute cholecystitis or cholangitis")
data$admission_prior %<>% ff_label("Number of admissions in 12 months")
data$pre_img_us %<>% ff_label("Ultrasound scan (USS)")
data$pre_img_ct %<>% ff_label("Computed Tomography (CT)")
data$pre_img_mrcp %<>% ff_label("Magnetic Resonance Cholangiopancreatography (MRCP)")
data$pre_img_ercp %<>% ff_label("Endoscopic Retrograde Cholangiopancreatography (ERCP)")
data$pre_img_eus %<>% ff_label("Endoscopic Ultrasound (EUS)")
data$pre_img_hida %<>% ff_label("Hepatobiliary IminoDiacetic Acid (HIDA)")
data$pre_img_finding %<>% ff_label("Preoperative imaging findings")
data$pre_img_finding_cbd %<>% ff_label("Dilated CBD diameter")
data$pre_symp_adm_day %<>% ff_label("Days between first biliary symptom onset and diagnosis")
data$pre_diag_dec_day %<>% ff_label("Days between diagnosis and decision to operate")
data$pre_dec_op_day %<>% ff_label("Days between decision to operate and surgery performed")
data$pre_urgency %<>% ff_label("Urgency of surgery")
data$pre_indication %<>% ff_label("Indication of surgery")
data$pre_indication_tg %<>% ff_label("Tokyo grade")
data$pre_indication_atlanta %<>% ff_label("Atlanta criteria")
data$op_anaes %<>% ff_label("Mode of anaesthesia")
data$op_abx_yn %<>% ff_label("Intraoperative antibiotics")
data$op_operator %<>% ff_label("Primary operator")
data$op_operator_cons %<>% ff_label("Consultant specialty")
data$op_approach_mis_reuse %<>% ff_label("Reusable laparoscopic equipment")
data$op_nassar %<>% ff_label("Nassar grade")
data$op_cvs_yn %<>% ff_label("Critical View of Safety (CVS)")
data$op_drain_yn %<>% ff_label("Abdominal drain insertion")
data$op_biliary_var %<>% ff_label("Anatomical Biliary variant")
data$op_img %<>% ff_label("Intraoperative CBD Assessment")
data$op_cbd_explore %<>% ff_label("Common Bile Duct exploration")
data$op_cbd_explore_close %<>% ff_label("Choledochotomy closure")
data$op_contam %<>% ff_label("Operative contamination")
data$op_comp %<>% ff_label("Intraoperative complications")
data$op_reuse_gown %<>% ff_label("Rreusable gowns")
data$op_reuse_drape %<>% ff_label("Reusable drapes")
data$postop30_cd %<>% ff_label("30-day Clavien Dindo Complication")
data$postop30_cc_yn %<>% ff_label("Unplanned critical care admission")
data$postop30_reimg %<>% ff_label("Unplanned re-imaging")
data$postop30_comp_ssi %<>% ff_label("Surgical site infection")
data$postop30_comp_ppc %<>% ff_label("Postoperative pulmonary complications")
data$postop30_comp_leak %<>% ff_label("Bile leak")
data$postop30_comp_collec %<>% ff_label("Intra-abdominal collection")
data$postop30_comp_ap %<>% ff_label("Acute pancreatitis")
data$post30_los %<>% ff_label("Length of stay")
data$postop30_readm %<>% ff_label("30-day readmission")
data$bdi_yn %<>% ff_label("Bile Duct Injury (BDI)")
data$hist_exam_yn %<>% ff_label("Histological specimen sent for examination")
data$postop30_cd_drain %<>% ff_label("Radiological drainage")
data$postop30_cd_reop %<>% ff_label("Re-operation")
data$postop30_comp_bleed %<>% ff_label("Bleeding")



