library(finalfit)
library(magrittr)
#Setting Labels

data$record_id%<>% ff_label("Record ID")
data$redcap_data_access_group%<>% ff_label("Data Access Group")
data$hosp_type%<>% ff_label(" Hospital type  (Please select the option which best describes your hospital.)")
data$hosp_fund%<>% ff_label(" Hospital funding")
data$hosp_bed%<>% ff_label(" Total number of inpatient beds  (Please include both surgical and non-surgical beds.)")
data$hosp_itu_yn%<>% ff_label(" Do you have Level 2 (HDU) or Level 3 (ITU) facilities at your hospital?")
data$hosp_itu_bed%<>% ff_label(" Total number of Level 2 (HDU) or Level 3 (ITU) beds")
data$hosp_hpb%<>% ff_label(" Do you have a specialised HPB team at your hospital?")
data$hosp_hpb_oncall%<>% ff_label(" Are there on-call services from the specialised HPB team?")
data$hosp_hpb_path%<>% ff_label(" Does the specialised HPB team have a dedicated pathway for management of bile duct injury?")
data$hosp_hpb_region%<>% ff_label(" Are there on-call surgeons specialised in HPB?")
data$hosp_mis_yn%<>% ff_label(" Do you have access to minimally invasive surgical equipment?")
data$hosp_mis_type%<>% ff_label(" Type of minimally invasive surgical equipment available")
data$hosp_mis_image%<>% ff_label(" Do you routinely take intraoperative images at your hospital?")
data$service_chole_n%<>% ff_label(" What is the approximate total number of cholecystectomies performed each year at your hospital?")
data$service_cons_n%<>% ff_label(" What is the number of consultant/attending surgeons who perform cholecystectomies each year at your hospital?")
data$service_cons_lap_n%<>% ff_label(" What is the number of consultant/attending surgeons who perform laparoscopic cholecystectomy at your hospital?")
data$service_cons_type%<>% ff_label(" Which specialist consultant/attending surgeons perform cholecystectomies at your hospital?")
data$service_type%<>% ff_label(" What type of services for cholecystectomy services is provided at your hospital?")
data$service_eme_n%<>% ff_label(" What is the approximate total number of emergency cholecystectomies performed each year at your hospital?")
data$service_eme_theatre%<>% ff_label(" Do you have dedicated theatres for these emergency services?")
data$service_setting%<>% ff_label(" Where are cholecystectomies performed at your hospital?  ")
data$service_fu%<>% ff_label(" Do you follow-up after cholecystectomy?")
data$diag_us_yn%<>% ff_label(" Ultrasound")
data$diag_ct_yn%<>% ff_label(" Computerised Tomography (CT)")
data$diag_mrcp_yn%<>% ff_label(" Magnetic Resonance Cholangiopancreatography (MRCP)")
data$diag_eus_yn%<>% ff_label(" Endoscopic Ultrasound (EUS)")
data$diag_hida_yn%<>% ff_label(" Hepatobiliary Iminodiacetic Acid (HIDA)")
data$diag_ostomy_yn%<>% ff_label(" Does your hospital have access to cholecystostomy for gallbladder drainage?")
data$diag_ostomy_oncall%<>% ff_label(" Are there on-call services for cholecystostomy at your hospital?")
data$diag_ostomy_region%<>% ff_label(" Are there on-call interventional radiologists who perform cholecystostomy available?")
data$diag_ercp%<>% ff_label(" Is there a dedicated Endoscopic retrograde cholangiopancreatography (ERCP) list at your hospital?")
data$diag_ioc%<>% ff_label(" Intraoperative Cholangiogram (IOC)")
data$diag_lu%<>% ff_label(" Laparoscopic Ultrasound")
data$diag_icg%<>% ff_label(" Incisionless fluorescent cholangiography")
data$diag_hist%<>% ff_label(" Do you send gallbladders for histological examination after surgery?")
data$train_perform%<>% ff_label(" Are there trainees in the department who perform gallbladder surgery?")
data$train_n%<>% ff_label(" How many trainees are there in the department who perform gallbladder surgery?")
data$train_grade%<>% ff_label(" What are the trainees grades who perform gallbladder surgery in your department?")
data$train_sim_yn%<>% ff_label(" Are there facilities for simulations training for cholecystectomies?")
data$train_sim_type%<>% ff_label(" What are the types of simulation training available?")
data$tain_chole%<>% ff_label(" Are there structured educational programmes or coaching for cholecystectomy training?")
data$train_bdi%<>% ff_label(" Are there specific structured educational programmes or coaching for bile duct injury training?")
data$green_lap%<>% ff_label(" Are reusable laparoscopic ports used?")
data$green_surginst%<>% ff_label(" Are reusable surgical instruments used?")
data$green_drape%<>% ff_label(" Are reusable drapes used?")
data$green_gown%<>% ff_label(" Are reusable gowns used?")
data$green_scrubcap%<>% ff_label(" Are reusable scrub caps used?")
data$green_recycle%<>% ff_label(" Are single-use instruments recycled?")
data$green_recycle_waste%<>% ff_label(" Are clean paper and plastic waste recycled?")
data$green_ga%<>% ff_label(" Is general anaesthesia given through IV rather than anaesthetic gases for environmental reasons?")
data$site_survey_complete%<>% ff_label("Complete?")
data$data_collection_dag%<>% ff_label("Data dag:")
data$admin_complete%<>% ff_label("Complete?")

data$hosp_type = factor(data$hosp_type,levels=c("1","2","3"))
data$hosp_fund = factor(data$hosp_fund,levels=c("1","2","3"))
data$hosp_itu_yn = factor(data$hosp_itu_yn,levels=c("1","0"))
data$hosp_hpb = factor(data$hosp_hpb,levels=c("1","0"))
data$hosp_hpb_oncall = factor(data$hosp_hpb_oncall,levels=c("1","2","3","4"))
data$hosp_hpb_path = factor(data$hosp_hpb_path,levels=c("1","0"))
data$hosp_hpb_region = factor(data$hosp_hpb_region,levels=c("1","2","3","4"))
data$hosp_mis_yn = factor(data$hosp_mis_yn,levels=c("1","0"))
data$hosp_mis_image = factor(data$hosp_mis_image,levels=c("1","2","3","4"))
data$service_eme_theatre = factor(data$service_eme_theatre,levels=c("1","2","3","4","5"))
data$service_fu = factor(data$service_fu,levels=c("1","2","3"))
data$diag_us_yn = factor(data$diag_us_yn,levels=c("1","2","3"))
data$diag_ct_yn = factor(data$diag_ct_yn,levels=c("1","2","3"))
data$diag_mrcp_yn = factor(data$diag_mrcp_yn,levels=c("1","2","3"))
data$diag_eus_yn = factor(data$diag_eus_yn,levels=c("1","2","3"))
data$diag_hida_yn = factor(data$diag_hida_yn,levels=c("1","2","3"))
data$diag_ostomy_yn = factor(data$diag_ostomy_yn,levels=c("1","0"))
data$diag_ostomy_oncall = factor(data$diag_ostomy_oncall,levels=c("1","2","3","4","5"))
data$diag_ostomy_region = factor(data$diag_ostomy_region,levels=c("1","2","3","4"))
data$diag_ercp = factor(data$diag_ercp,levels=c("1","2","3","4","5"))
data$diag_ioc = factor(data$diag_ioc,levels=c("1","2","3","4"))
data$diag_lu = factor(data$diag_lu,levels=c("1","2","3","4"))
data$diag_icg = factor(data$diag_icg,levels=c("1","2","3","4"))
data$diag_hist = factor(data$diag_hist,levels=c("1","2","3","4"))
data$train_perform = factor(data$train_perform,levels=c("1","0"))
data$green_lap = factor(data$green_lap,levels=c("1","2","3","4"))
data$green_surginst = factor(data$green_surginst,levels=c("1","2","3","4"))
data$green_drape = factor(data$green_drape,levels=c("1","2","3","4"))
data$green_gown = factor(data$green_gown,levels=c("1","2","3","4"))
data$green_scrubcap = factor(data$green_scrubcap,levels=c("1","2","3","4"))
data$green_recycle = factor(data$green_recycle,levels=c("1","2","3","4"))
data$green_recycle_waste = factor(data$green_recycle_waste,levels=c("1","0"))
data$green_ga = factor(data$green_ga,levels=c("1","2","3","4"))
data$site_survey_complete = factor(data$site_survey_complete,levels=c("0","1","2"))
data$admin_complete = factor(data$admin_complete,levels=c("0","1","2"))


levels(data$hosp_type)=c("District (Rural)","District (Non-rural)","Tertiary (teaching or university hospital)")
levels(data$hosp_fund)=c("Public","Private","Mixed")
levels(data$hosp_itu_yn)=c("Yes","No")
levels(data$hosp_hpb)=c("Yes","No")
levels(data$hosp_hpb_oncall)=c("Every day (24 hour)","Every day (daytime 0800 - 1700)","Weekdays only (24 hour)","Weekdays only (daytime 0800 - 1700)")
levels(data$hosp_hpb_path)=c("Yes","No")
levels(data$hosp_hpb_region)=c("Within the same city","In another city but in the same region","In another region","None")
levels(data$hosp_mis_yn)=c("Yes","No")
levels(data$hosp_mis_image)=c("Yes (Photo only)","Yes (Video only)","Yes (Photo and Video)","No")
levels(data$service_eme_theatre)=c("Yes (Everyday)","Yes (Once a week)","Yes (Once every 2 week)","Yes (More than once every 2 weeks)","No")
levels(data$service_fu)=c("Yes (Routinely)","Yes (Selectively)","No")
levels(data$diag_us_yn)=c("Available on-site","Available off-site","Not available")
levels(data$diag_ct_yn)=c("Available on-site","Available off-site","Not available")
levels(data$diag_mrcp_yn)=c("Available on-site","Available off-site","Not available")
levels(data$diag_eus_yn)=c("Available on-site","Available off-site","Not available")
levels(data$diag_hida_yn)=c("Available on-site","Available off-site","Not available")
levels(data$diag_ostomy_yn)=c("Yes","No")
levels(data$diag_ostomy_oncall)=c("Yes (Everyday)","Yes (Once a week)","Yes (Once every 2 week)","Yes (More than once every 2 weeks)","No")
levels(data$diag_ostomy_region)=c("Within the same city","In another city but in the same region","In another region","None")
levels(data$diag_ercp)=c("Yes (Everyday)","Yes (Once a week)","Yes (Once every 2 week)","Yes (More than once every 2 weeks)","No")
levels(data$diag_ioc)=c("Routine use","Selective use with good supply","Selective use with limited supply","Not available")
levels(data$diag_lu)=c("Routine use","Selective use with good supply","Selective use with limited supply","Not available")
levels(data$diag_icg)=c("Routine use","Selective use with good supply","Selective use with limited supply","Not available")
levels(data$diag_hist)=c("Yes (Routinely)","Yes (Selectively)","No (Not sent for histology)","No (No access to histology)")
levels(data$train_perform)=c("Yes","No")
levels(data$green_lap)=c("Yes (Always)","Yes (Sometimes)","No (Not used but available)","No (Not available)")
levels(data$green_surginst)=c("Yes (Always)","Yes (Sometimes)","No (Not used but available)","No (Not available)")
levels(data$green_drape)=c("Yes (Always)","Yes (Sometimes)","No (Not used but available)","No (Not available)")
levels(data$green_gown)=c("Yes (Always)","Yes (Sometimes)","No (Not used but available)","No (Not available)")
levels(data$green_scrubcap)=c("Yes (Always)","Yes (Sometimes)","No (Not used but available)","No (Not available)")
levels(data$green_recycle)=c("Yes (Always)","Yes (Sometimes)","No (Not recycled but recycling service available)","No (No recycling service available)")
levels(data$green_recycle_waste)=c("Yes","No")
levels(data$green_ga)=c("Yes (Always)","Yes (Sometimes)","No (Anaesthetic gases used but IV anaesthesia available)","No (No IV anaesthesia available)")
levels(data$site_survey_complete)=c("Incomplete","Unverified","Complete")
levels(data$admin_complete)=c("Incomplete","Unverified","Complete")
