library(finalfit)
library(magrittr)

data$postop1yr_cd = factor(data$postop1yr_cd,levels=c("1","2","3","4","5","6","7","8"))
data$postop1yr_cd_drain = factor(data$postop1yr_cd_drain,levels=c("1","0"))
data$postop1yr_cd_ercp = factor(data$postop1yr_cd_ercp,levels=c("1","0"))
data$postop1yr_cd_reop = factor(data$postop1yr_cd_reop,levels=c("1","0"))
data$postop1yr_cd_reop_type___1 = factor(data$postop1yr_cd_reop_type___1,levels=c("0","1"))
data$postop1yr_cd_reop_type___2 = factor(data$postop1yr_cd_reop_type___2,levels=c("0","1"))
data$postop1yr_comp_ssi = factor(data$postop1yr_comp_ssi,levels=c("1","2","3","4","5","6","7","8"))
data$postop1yr_comp_ppc = factor(data$postop1yr_comp_ppc,levels=c("1","2","3","4","5","6","7","8"))
data$postop1yr_comp_leak = factor(data$postop1yr_comp_leak,levels=c("1","2","3","4","5","6","7","8"))
data$postop1yr_comp_strict = factor(data$postop1yr_comp_strict,levels=c("1","2","3","4","5","6","7","8"))
data$postop1yr_comp_bleed = factor(data$postop1yr_comp_bleed,levels=c("1","2","3","4","5","6","7","8"))
data$postop1yr_comp_collec = factor(data$postop1yr_comp_collec,levels=c("1","2","3","4","5","6","7","8"))
data$postop1yr_comp_ap = factor(data$postop1yr_comp_ap,levels=c("1","2","3","4","5","6","7","8"))
data$postop1yr_comp_calc = factor(data$postop1yr_comp_calc,levels=c("1","2","3","4","5","6","7","8"))
data$postop1yr_comp_chol = factor(data$postop1yr_comp_chol,levels=c("1","2","3","4","5","6","7","8"))
data$postop1yr_comp_reman = factor(data$postop1yr_comp_reman,levels=c("1","2","3","4","5","6","7","8"))
data$postop1yr_comp_hernia = factor(data$postop1yr_comp_hernia,levels=c("1","2","3","4","5","6","7","8"))
data$oneyear_outcomes_complete = factor(data$oneyear_outcomes_complete,levels=c("0","1","2"))

levels(data$postop1yr_cd)=c("0 (no complications)","I","II","IIIa","IIIb","IVa","IVb","V (death)")
levels(data$postop1yr_cd_drain)=c("Yes","No")
levels(data$postop1yr_cd_ercp)=c("Yes","No")
levels(data$postop1yr_cd_reop)=c("Yes","No")
levels(data$postop1yr_cd_reop_type___1)=c("Unchecked","Checked")
levels(data$postop1yr_cd_reop_type___2)=c("Unchecked","Checked")
levels(data$postop1yr_comp_ssi)=c("0 (no complication)","I","II","IIIa","IIIb","IVa","IVb","V (death)")
levels(data$postop1yr_comp_ppc)=c("0 (no complication)","I","II","IIIa","IIIb","IVa","IVb","V (death)")
levels(data$postop1yr_comp_leak)=c("0 (no complication)","I","II","IIIa","IIIb","IVa","IVb","V (death)")
levels(data$postop1yr_comp_strict)=c("0 (no complication)","I","II","IIIa","IIIb","IVa","IVb","V (death)")
levels(data$postop1yr_comp_bleed)=c("0 (no complication)","I","II","IIIa","IIIb","IVa","IVb","V (death)")
levels(data$postop1yr_comp_collec)=c("0 (no complication)","I","II","IIIa","IIIb","IVa","IVb","V (death)")
levels(data$postop1yr_comp_ap)=c("0 (no complication)","I","II","IIIa","IIIb","IVa","IVb","V (death)")
levels(data$postop1yr_comp_calc)=c("0 (no complication)","I","II","IIIa","IIIb","IVa","IVb","V (death)")
levels(data$postop1yr_comp_chol)=c("0 (no complication)","I","II","IIIa","IIIb","IVa","IVb","V (death)")
levels(data$postop1yr_comp_reman)=c("0 (no complication)","I","II","IIIa","IIIb","IVa","IVb","V (death)")
levels(data$postop1yr_comp_hernia)=c("0 (no complication)","I","II","IIIa","IIIb","IVa","IVb","V (death)")
levels(data$oneyear_outcomes_complete)=c("Incomplete","Unverified","Complete")


# Labelling ----
data$record_id %<>% ff_label("Record ID")
data$redcap_data_access_group %<>% ff_label("Data Access Group")
data$postop1yr_cd %<>% ff_label("Highest one-year Clavien Dindo Complication Grade (Clavien-Dindo Classification found here)")
data$postop1yr_cd_drain %<>% ff_label("Radiological drainage")
data$postop1yr_cd_ercp %<>% ff_label("ERCP (i.e., diagnostic or therapeutic)")
data$postop1yr_cd_reop %<>% ff_label("Re-operation")
data$postop1yr_cd_reop_type___1 %<>% ff_label("Type of re-operation  (choice=Completion cholecystectomy)")
data$postop1yr_cd_reop_type___2 %<>% ff_label("Type of re-operation  (choice=Reconstructive surgical procedures)")
data$postop1yr_cd_death %<>% ff_label("Time from index cholecystectomy to death")
data$postop1yr_cd_death_month %<>% ff_label("Time of death in months")
data$postop1yr_readm %<>% ff_label("Total number of readmissions ")
data$postop1yr_readm_chole %<>% ff_label("Total number of readmissions related to index cholecystectomy")
data$postop1yr_comp_ssi %<>% ff_label("Surgical site infection")
data$postop1yr_comp_ppc %<>% ff_label("Postoperative pulmonary complications")
data$postop1yr_comp_leak %<>% ff_label("Bile leak")
data$postop1yr_comp_strict %<>% ff_label("Biliary stricture")
data$postop1yr_comp_bleed %<>% ff_label("Bleeding")
data$postop1yr_comp_collec %<>% ff_label("Intra-abdominal collection")
data$postop1yr_comp_ap %<>% ff_label("Acute pancreatitis")
data$postop1yr_comp_calc %<>% ff_label("Calculus bile duct obstruction (choledocholithiasis)")
data$postop1yr_comp_chol %<>% ff_label("Cholangitis")
data$postop1yr_comp_reman %<>% ff_label("Remnant (acute) cholecystitis")
data$postop1yr_comp_hernia %<>% ff_label("Incisional hernia")
data$oneyear_outcomes_complete %<>% ff_label("Complete?")