##Clear existing data and graphics
#rm(list=ls())
#graphics.off()
##Load Hmisc library
#library(Hmisc)
##Read Data
#data=read.csv('GECKOTeamRegistratio_DATA_2024-01-10_1423.csv')

library(finalfit)
library(magrittr)






#Setting Factors(will create new variable for factors)
data$ethics = factor(data$ethics,levels=c("1","2","3"))
data$ethics_2 = factor(data$ethics_2,levels=c("1","0"))
data$hl_grade = factor(data$hl_grade,levels=c("1","2"))
data$period___1 = factor(data$period___1,levels=c("0","1"))
data$period___2 = factor(data$period___2,levels=c("0","1"))
data$period___3 = factor(data$period___3,levels=c("0","1"))
data$period___4 = factor(data$period___4,levels=c("0","1"))
data$period___5 = factor(data$period___5,levels=c("0","1"))
data$period___6 = factor(data$period___6,levels=c("0","1"))
data$period___7 = factor(data$period___7,levels=c("0","1"))
data$period___8 = factor(data$period___8,levels=c("0","1"))
data$p1_miniteam_size = factor(data$p1_miniteam_size,levels=c("1","2","3","4","5"))
data$p2_miniteam_size = factor(data$p2_miniteam_size,levels=c("1","2","3","4","5"))
data$p3_miniteam_size = factor(data$p3_miniteam_size,levels=c("1","2","3","4","5"))
data$p4_miniteam_size = factor(data$p4_miniteam_size,levels=c("1","2","3","4","5"))
data$p5_miniteam_size = factor(data$p5_miniteam_size,levels=c("1","2","3","4","5"))
data$p6_miniteam_size = factor(data$p6_miniteam_size,levels=c("1","2","3","4","5"))
data$p7_miniteam_size = factor(data$p7_miniteam_size,levels=c("1","2","3","4","5"))
data$p8_miniteam_size = factor(data$p8_miniteam_size,levels=c("1","2","3","4","5"))
data$miniteam_application_portal_complete = factor(data$miniteam_application_portal_complete,levels=c("0","1","2"))
data$hosp_type = factor(data$hosp_type,levels=c("1","2","3"))
data$hosp_fund = factor(data$hosp_fund,levels=c("1","2","3"))
data$hosp_itu_yn = factor(data$hosp_itu_yn,levels=c("1","0"))
data$hosp_hpb = factor(data$hosp_hpb,levels=c("1","0"))
data$hosp_hpb_oncall = factor(data$hosp_hpb_oncall,levels=c("1","2","3","4"))
data$hosp_hpb_path = factor(data$hosp_hpb_path,levels=c("1","0"))
data$hosp_hpb_region = factor(data$hosp_hpb_region,levels=c("1","2","3","4"))
data$hosp_mis_yn = factor(data$hosp_mis_yn,levels=c("1","0"))
data$hosp_mis_type___1 = factor(data$hosp_mis_type___1,levels=c("0","1"))
data$hosp_mis_type___2 = factor(data$hosp_mis_type___2,levels=c("0","1"))
data$hosp_mis_image = factor(data$hosp_mis_image,levels=c("1","2","3","4"))
data$service_cons_type___1 = factor(data$service_cons_type___1,levels=c("0","1"))
data$service_cons_type___2 = factor(data$service_cons_type___2,levels=c("0","1"))
data$service_cons_type___3 = factor(data$service_cons_type___3,levels=c("0","1"))
data$service_cons_type___4 = factor(data$service_cons_type___4,levels=c("0","1"))
data$service_cons_type___5 = factor(data$service_cons_type___5,levels=c("0","1"))
data$service_cons_type___6 = factor(data$service_cons_type___6,levels=c("0","1"))
data$service_type___1 = factor(data$service_type___1,levels=c("0","1"))
data$service_type___2 = factor(data$service_type___2,levels=c("0","1"))
data$service_eme_theatre = factor(data$service_eme_theatre,levels=c("1","2","3","4","5"))
data$service_setting___1 = factor(data$service_setting___1,levels=c("0","1"))
data$service_setting___2 = factor(data$service_setting___2,levels=c("0","1"))
data$service_setting___3 = factor(data$service_setting___3,levels=c("0","1"))
data$service_fu = factor(data$service_fu,levels=c("1","2","3"))
data$diag_us_yn = factor(data$diag_us_yn,levels=c("1","2","3"))
data$diag_ct_yn = factor(data$diag_ct_yn,levels=c("1","2","3"))
data$diag_mrcp_yn = factor(data$diag_mrcp_yn,levels=c("1","2","3"))
data$diag_eus_yn = factor(data$diag_eus_yn,levels=c("1","2","3"))
data$diag_hida_yn = factor(data$diag_hida_yn,levels=c("1","2","3"))
data$diag_ostomy_yn = factor(data$diag_ostomy_yn,levels=c("1","0"))
data$diag_ostomy_oncall = factor(data$diag_ostomy_oncall,levels=c("1","2","3","4","5"))
data$diag_ostomy_region = factor(data$diag_ostomy_region,levels=c("1","2","3","4"))
data$diag_ercp = factor(data$diag_ercp,levels=c("1","2","3","4","5"))
data$diag_ioc = factor(data$diag_ioc,levels=c("1","2","3","4"))
data$diag_lu = factor(data$diag_lu,levels=c("1","2","3","4"))
data$diag_icg = factor(data$diag_icg,levels=c("1","2","3","4"))
data$diag_hist = factor(data$diag_hist,levels=c("1","2","3","4"))
data$train_perform = factor(data$train_perform,levels=c("1","0"))
data$train_grade___1 = factor(data$train_grade___1,levels=c("0","1"))
data$train_grade___2 = factor(data$train_grade___2,levels=c("0","1"))
data$train_grade___3 = factor(data$train_grade___3,levels=c("0","1"))
data$train_grade___4 = factor(data$train_grade___4,levels=c("0","1"))
data$train_sim_yn___1 = factor(data$train_sim_yn___1,levels=c("0","1"))
data$train_sim_yn___2 = factor(data$train_sim_yn___2,levels=c("0","1"))
data$train_sim_yn___3 = factor(data$train_sim_yn___3,levels=c("0","1"))
data$train_sim_yn___4 = factor(data$train_sim_yn___4,levels=c("0","1"))
data$train_sim_type___1 = factor(data$train_sim_type___1,levels=c("0","1"))
data$train_sim_type___2 = factor(data$train_sim_type___2,levels=c("0","1"))
data$train_sim_type___3 = factor(data$train_sim_type___3,levels=c("0","1"))
data$tain_chole___1 = factor(data$tain_chole___1,levels=c("0","1"))
data$tain_chole___2 = factor(data$tain_chole___2,levels=c("0","1"))
data$tain_chole___3 = factor(data$tain_chole___3,levels=c("0","1"))
data$tain_chole___4 = factor(data$tain_chole___4,levels=c("0","1"))
data$train_bdi___1 = factor(data$train_bdi___1,levels=c("0","1"))
data$train_bdi___2 = factor(data$train_bdi___2,levels=c("0","1"))
data$train_bdi___3 = factor(data$train_bdi___3,levels=c("0","1"))
data$train_bdi___4 = factor(data$train_bdi___4,levels=c("0","1"))
data$green_lap = factor(data$green_lap,levels=c("1","2","3","4"))
data$green_surginst = factor(data$green_surginst,levels=c("1","2","3","4"))
data$green_drape = factor(data$green_drape,levels=c("1","2","3","4"))
data$green_gown = factor(data$green_gown,levels=c("1","2","3","4"))
data$green_scrubcap = factor(data$green_scrubcap,levels=c("1","2","3","4"))
data$green_recycle = factor(data$green_recycle,levels=c("1","2","3","4"))
data$green_recycle_waste = factor(data$green_recycle_waste,levels=c("1","0"))
data$green_ga = factor(data$green_ga,levels=c("1","2","3","4"))
data$site_survey_complete = factor(data$site_survey_complete,levels=c("0","1","2"))
data$admin_complete = factor(data$admin_complete,levels=c("0","1","2"))

levels(data$ethics)%<>% ff_label(c("I do NOT expect to receive local study approval to participate in GECKO","I have applied for the necessary local study approvals and expect these to be approved before data lock","I have applied for the necessary local study approvals and these have been successfully confirmed"))
levels(data$ethics_2)%<>% ff_label(c("Yes","No"))
levels(data$hl_grade)%<>% ff_label(c("Surgical Trainee (registrar/resident)","Consultant/Attending"))
levels(data$period___1 )%<>% ff_label(c("Unchecked","Checked"))
levels(data$period___2)%<>% ff_label(c("Unchecked","Checked"))
levels(data$period___3)%<>% ff_label(c("Unchecked","Checked"))
levels(data$period___4)%<>% ff_label(c("Unchecked","Checked"))
levels(data$period___5)%<>% ff_label(c("Unchecked","Checked"))
levels(data$period___6)%<>% ff_label(c("Unchecked","Checked"))
levels(data$period___7)%<>% ff_label(c("Unchecked","Checked"))
levels(data$period___8)%<>% ff_label(c("Unchecked","Checked"))
levels(data$p1_miniteam_size)%<>% ff_label(c("1","2","3","4","5"))
levels(data$p2_miniteam_size)%<>% ff_label(c("1","2","3","4","5"))
levels(data$p3_miniteam_size)%<>% ff_label(c("1","2","3","4","5"))
levels(data$p4_miniteam_size)%<>% ff_label(c("1","2","3","4","5"))
levels(data$p5_miniteam_size)%<>% ff_label(c("1","2","3","4","5"))
levels(data$p6_miniteam_size)%<>% ff_label(c("1","2","3","4","5"))
levels(data$p7_miniteam_size)%<>% ff_label(c("1","2","3","4","5"))
levels(data$p8_miniteam_size)%<>% ff_label(c("1","2","3","4","5"))
levels(data$miniteam_application_portal_complete)%<>% ff_label(c("Incomplete","Unverified","Complete"))
levels(data$hosp_type)%<>% ff_label(c("District (Rural)","District (Non-rural)","Tertiary (teaching or university hospital)"))
levels(data$hosp_fund)%<>% ff_label(c("Public","Private","Mixed"))
levels(data$hosp_itu_yn)%<>% ff_label(c("Yes","No"))
levels(data$hosp_hpb)%<>% ff_label(c("Yes","No"))
levels(data$hosp_hpb_oncall)%<>% ff_label(c("Every day (24 hour)","Every day (daytime 0800 - 1700)","Weekdays only (24 hour)","Weekdays only (daytime 0800 - 1700)"))
levels(data$hosp_hpb_path)%<>% ff_label(c("Yes","No"))
levels(data$hosp_hpb_region)%<>% ff_label(c("Within the same city","In another city but in the same region","In another region","None"))
levels(data$hosp_mis_yn)%<>% ff_label(c("Yes","No"))
levels(data$hosp_mis_type___1)%<>% ff_label(c("Unchecked","Checked"))
levels(data$hosp_mis_type___2)%<>% ff_label(c("Unchecked","Checked"))
levels(data$hosp_mis_image)%<>% ff_label(c("Yes (Photo only)","Yes (Video only)","Yes (Photo and Video)","No"))
levels(data$service_cons_type___1)%<>% ff_label(c("Unchecked","Checked"))
levels(data$service_cons_type___2)%<>% ff_label(c("Unchecked","Checked"))
levels(data$service_cons_type___3)%<>% ff_label(c("Unchecked","Checked"))
levels(data$service_cons_type___4)%<>% ff_label(c("Unchecked","Checked"))
levels(data$service_cons_type___5)%<>% ff_label(c("Unchecked","Checked"))
levels(data$service_cons_type___6)%<>% ff_label(c("Unchecked","Checked"))
levels(data$service_type___1)%<>% ff_label(c("Unchecked","Checked"))
levels(data$service_type___2)%<>% ff_label(c("Unchecked","Checked"))
levels(data$service_eme_theatre)%<>% ff_label(c("Yes (Everyday)","Yes (Once a week)","Yes (Once every 2 week)","Yes (More than once every 2 weeks)","No"))
levels(data$service_setting___1)%<>% ff_label(c("Unchecked","Checked"))
levels(data$service_setting___2)%<>% ff_label(c("Unchecked","Checked"))
levels(data$service_setting___3)%<>% ff_label(c("Unchecked","Checked"))
levels(data$service_fu)%<>% ff_label(c("Yes (Routinely)","Yes (Selectively)","No"))
levels(data$diag_us_yn)%<>% ff_label(c("Available on-site","Available off-site","Not available"))
levels(data$diag_ct_yn)%<>% ff_label(c("Available on-site","Available off-site","Not available"))
levels(data$diag_mrcp_yn)%<>% ff_label(c("Available on-site","Available off-site","Not available"))
levels(data$diag_eus_yn)%<>% ff_label(c("Available on-site","Available off-site","Not available"))
levels(data$diag_hida_yn)%<>% ff_label(c("Available on-site","Available off-site","Not available"))
levels(data$diag_ostomy_yn)%<>% ff_label(c("Yes","No"))
levels(data$diag_ostomy_oncall)%<>% ff_label(c("Yes (Everyday)","Yes (Once a week)","Yes (Once every 2 week)","Yes (More than once every 2 weeks)","No"))
levels(data$diag_ostomy_region)%<>% ff_label(c("Within the same city","In another city but in the same region","In another region","None"))
levels(data$diag_ercp)%<>% ff_label(c("Yes (Everyday)","Yes (Once a week)","Yes (Once every 2 week)","Yes (More than once every 2 weeks)","No"))
levels(data$diag_ioc)%<>% ff_label(c("Routine use","Selective use with good supply","Selective use with limited supply","Not available"))
levels(data$diag_lu)%<>% ff_label(c("Routine use","Selective use with good supply","Selective use with limited supply","Not available"))
levels(data$diag_icg)%<>% ff_label(c("Routine use","Selective use with good supply","Selective use with limited supply","Not available"))
levels(data$diag_hist)%<>% ff_label(c("Yes (Routinely)","Yes (Selectively)","No (Not sent for histology)","No (No access to histology)"))
levels(data$train_perform)%<>% ff_label(c("Yes","No"))
levels(data$train_grade___1)%<>% ff_label(c("Unchecked","Checked"))
levels(data$train_grade___2)%<>% ff_label(c("Unchecked","Checked"))
levels(data$train_grade___3)%<>% ff_label(c("Unchecked","Checked"))
levels(data$train_grade___4)%<>% ff_label(c("Unchecked","Checked"))
levels(data$train_sim_yn___1)%<>% ff_label(c("Unchecked","Checked"))
levels(data$train_sim_yn___2)%<>% ff_label(c("Unchecked","Checked"))
levels(data$train_sim_yn___3)%<>% ff_label(c("Unchecked","Checked"))
levels(data$train_sim_yn___4)%<>% ff_label(c("Unchecked","Checked"))
levels(data$train_sim_type___1)%<>% ff_label(c("Unchecked","Checked"))
levels(data$train_sim_type___2)%<>% ff_label(c("Unchecked","Checked"))
levels(data$train_sim_type___3)%<>% ff_label(c("Unchecked","Checked"))
levels(data$tain_chole___1)%<>% ff_label(c("Unchecked","Checked"))
levels(data$tain_chole___2)%<>% ff_label(c("Unchecked","Checked"))
levels(data$tain_chole___3)%<>% ff_label(c("Unchecked","Checked"))
levels(data$tain_chole___4)%<>% ff_label(c("Unchecked","Checked"))
levels(data$train_bdi___1)%<>% ff_label(c("Unchecked","Checked"))
levels(data$train_bdi___2)%<>% ff_label(c("Unchecked","Checked"))
levels(data$train_bdi___3)%<>% ff_label(c("Unchecked","Checked"))
levels(data$train_bdi___4)%<>% ff_label(c("Unchecked","Checked"))
levels(data$green_lap)%<>% ff_label(c("Yes (Always)","Yes (Sometimes)","No (Not used but available)","No (Not available)"))
levels(data$green_surginst)%<>% ff_label(c("Yes (Always)","Yes (Sometimes)","No (Not used but available)","No (Not available)"))
levels(data$green_drape)%<>% ff_label(c("Yes (Always)","Yes (Sometimes)","No (Not used but available)","No (Not available)"))
levels(data$green_gown)%<>% ff_label(c("Yes (Always)","Yes (Sometimes)","No (Not used but available)","No (Not available)"))
levels(data$green_scrubcap)%<>% ff_label(c("Yes (Always)","Yes (Sometimes)","No (Not used but available)","No (Not available)"))
levels(data$green_recycle)%<>% ff_label(c("Yes (Always)","Yes (Sometimes)","No (Not recycled but recycling service available)","No (No recycling service available)"))
levels(data$green_recycle_waste)%<>% ff_label(c("Yes","No"))
levels(data$green_ga)%<>% ff_label(c("Yes (Always)","Yes (Sometimes)","No (Anaesthetic gases used but IV anaesthesia available)","No (No IV anaesthesia available)"))
levels(data$site_survey_complete)%<>% ff_label(c("Incomplete","Unverified","Complete"))
levels(data$admin_complete)%<>% ff_label(c("Incomplete","Unverified","Complete"))

#Setting Labels

data$record_id%<>% ff_label("Record ID")
data$redcap_data_access_group%<>% ff_label("Data Access Group")
data$time_entered%<>% ff_label("Time of entry")
data$hospital%<>% ff_label(" Please select your hospital  (Start typing your hospital or city or country name to find your hospital. Please note: you may need to try different spellings. If applicable, please try entering names both with and without accented letters (é ö ç etc).)")
data$ethics%<>% ff_label(" Have all necessary study approvals been confirmed at [hospital] for GECKO?  (The approvals that are required to run GECKO vary between different hospitals - please refer to Protocol for more information.)")
data$ethics_2%<>% ff_label("You can register your team whilst local approval is being processed.  However, please ensure you do not upload any patient data on to REDCap until local study approval has been confirmed.")
data$hl_fn%<>% ff_label(" First name")
data$hl_ln%<>% ff_label(" Last name (family name) ")
data$hl_grade%<>% ff_label(" What is your level of training?")
data$hl_orcid%<>% ff_label(" ORCID ID  (If you do not have an ORCID account you should visit https://orcid.org/signin and click on Register now. Registration is quick and free.)")
data$hl_email%<>% ff_label("  Email  ")
data$cons_fn%<>% ff_label(" First name")
data$cons_ln%<>% ff_label(" Last name (family name) ")
data$cons_orcid%<>% ff_label(" ORCID ID  (If you do not have an ORCID account you should visit https://orcid.org/signin and click on Register now. Registration is quick and free.)")
data$cons_email%<>% ff_label("  Email  ")
data$period___1%<>% ff_label(" Which period(s) would the team like to apply for?  (You can collect data during one or more period - please tick all periods you wish to apply for.) (choice=Period 1: 00:00 31st Jul 2023 - 23:59 13th Aug 2023 (+ 30 Day Follow-up))")
data$period___2%<>% ff_label(" Which period(s) would the team like to apply for?  (You can collect data during one or more period - please tick all periods you wish to apply for.) (choice=Period 2: 00:00 14th Aug 2023 - 23:59 27th Aug 2023 (+ 30 Day Follow-up))")
data$period___3%<>% ff_label(" Which period(s) would the team like to apply for?  (You can collect data during one or more period - please tick all periods you wish to apply for.) (choice=Period 3: 00:00 28th Aug 2023 - 23:59 10th Sep 2023 (+ 30 Day Follow-up))")
data$period___4%<>% ff_label(" Which period(s) would the team like to apply for?  (You can collect data during one or more period - please tick all periods you wish to apply for.) (choice=Period 4: 00:00 11th Sep 2023 - 23:59 24th Sep 2023 (+ 30 Day Follow-up))")
data$period___5%<>% ff_label(" Which period(s) would the team like to apply for?  (You can collect data during one or more period - please tick all periods you wish to apply for.) (choice=Period 5: 00:00 25th Sep 2023 - 23:59 8th Oct 2023 (+ 30 Day Follow-up))")
data$period___6%<>% ff_label(" Which period(s) would the team like to apply for?  (You can collect data during one or more period - please tick all periods you wish to apply for.) (choice=Period 6: 00:00 9th Oct 2023 - 23:59 22nd Oct 2023 (+ 30 Day Follow-up))")
data$period___7%<>% ff_label(" Which period(s) would the team like to apply for?  (You can collect data during one or more period - please tick all periods you wish to apply for.) (choice=Period 7: 00:00 23rd Oct 2023 - 23:59 5th Nov 2023 (+ 30 Day Follow-up))")
data$period___8%<>% ff_label(" Which period(s) would the team like to apply for?  (You can collect data during one or more period - please tick all periods you wish to apply for.) (choice=Period 8: 00:00 6th Nov 2023 - 23:59 19th Nov 2023 (+ 30 Day Follow-up))")
data$p1_miniteam_size%<>% ff_label(" How many collaborators would you like to register as part of this mini-team? ")
data$p1_fn_c1%<>% ff_label(" First name")
data$p1_ln_c1%<>% ff_label(" Last name (family name) ")
data$p1_orcid_c1%<>% ff_label(" ORCID ID  (If the collaborator do not have an ORCID account they should visit https://orcid.org/signin and click on Register now. Registration is quick and free.)")
data$p1_email_c1%<>% ff_label("  Email  ")
data$p1_fn_c2%<>% ff_label(" First name")
data$p1_ln_c2%<>% ff_label(" Last name (family name) ")
data$p1_orcid_c2%<>% ff_label(" ORCID ID  (If the collaborator do not have an ORCID account they should visit https://orcid.org/signin and click on Register now. Registration is quick and free.)")
data$p1_email_c2%<>% ff_label("  Email  ")
data$p1_fn_c3%<>% ff_label(" First name")
data$p1_ln_c3%<>% ff_label(" Last name (family name) ")
data$p1_orcid_c3%<>% ff_label(" ORCID ID  (If the collaborator do not have an ORCID account they should visit https://orcid.org/signin and click on Register now. Registration is quick and free.)")
data$p1_email_c3%<>% ff_label("  Email  ")
data$p1_fn_c4%<>% ff_label(" First name")
data$p1_ln_c4%<>% ff_label(" Last name (family name) ")
data$p1_orcid_c4%<>% ff_label(" ORCID ID  (If the collaborator do not have an ORCID account they should visit https://orcid.org/signin and click on Register now. Registration is quick and free.)")
data$p1_email_c4%<>% ff_label("  Email  ")
data$p1_fn_c5%<>% ff_label(" First name")
data$p1_ln_c5%<>% ff_label(" Last name (family name) ")
data$p1_orcid_c5%<>% ff_label(" ORCID ID  (If the collaborator do not have an ORCID account they should visit https://orcid.org/signin and click on Register now. Registration is quick and free.)")
data$p1_email_c5%<>% ff_label("  Email  ")
data$p2_miniteam_size%<>% ff_label(" How many collaborators would you like to register as part of this mini-team? ")
data$p2_fn_c1%<>% ff_label(" First name")
data$p2_ln_c1%<>% ff_label(" Last name (family name) ")
data$p2_orcid_c1%<>% ff_label(" ORCID ID  (If the collaborator do not have an ORCID account they should visit https://orcid.org/signin and click on Register now. Registration is quick and free.)")
data$p2_email_c1%<>% ff_label("  Email  ")
data$p2_fn_c2%<>% ff_label(" First name")
data$p2_ln_c2%<>% ff_label(" Last name (family name) ")
data$p2_orcid_c2%<>% ff_label(" ORCID ID  (If the collaborator do not have an ORCID account they should visit https://orcid.org/signin and click on Register now. Registration is quick and free.)")
data$p2_email_c2%<>% ff_label("  Email  ")
data$p2_fn_c3%<>% ff_label(" First name")
data$p2_ln_c3%<>% ff_label(" Last name (family name) ")
data$p2_orcid_c3%<>% ff_label(" ORCID ID  (If the collaborator do not have an ORCID account they should visit https://orcid.org/signin and click on Register now. Registration is quick and free.)")
data$p2_email_c3%<>% ff_label("  Email  ")
data$p2_fn_c4%<>% ff_label(" First name")
data$p2_ln_c4%<>% ff_label(" Last name (family name) ")
data$p2_orcid_c4%<>% ff_label(" ORCID ID  (If the collaborator do not have an ORCID account they should visit https://orcid.org/signin and click on Register now. Registration is quick and free.)")
data$p2_email_c4%<>% ff_label("  Email  ")
data$p2_fn_c5%<>% ff_label(" First name")
data$p2_ln_c5%<>% ff_label(" Last name (family name) ")
data$p2_orcid_c5%<>% ff_label(" ORCID ID  (If the collaborator do not have an ORCID account they should visit https://orcid.org/signin and click on Register now. Registration is quick and free.)")
data$p2_email_c5%<>% ff_label("  Email  ")
data$p3_miniteam_size%<>% ff_label(" How many collaborators would you like to register as part of this mini-team? ")
data$p3_fn_c1%<>% ff_label(" First name")
data$p3_ln_c1%<>% ff_label(" Last name (family name) ")
data$p3_orcid_c1%<>% ff_label(" ORCID ID  (If the collaborator do not have an ORCID account they should visit https://orcid.org/signin and click on Register now. Registration is quick and free.)")
data$p3_email_c1%<>% ff_label("  Email  ")
data$p3_fn_c2%<>% ff_label(" First name")
data$p3_ln_c2%<>% ff_label(" Last name (family name) ")
data$p3_orcid_c2%<>% ff_label(" ORCID ID  (If the collaborator do not have an ORCID account they should visit https://orcid.org/signin and click on Register now. Registration is quick and free.)")
data$p3_email_c2%<>% ff_label("  Email  ")
data$p3_fn_c3%<>% ff_label(" First name")
data$p3_ln_c3%<>% ff_label(" Last name (family name) ")
data$p3_orcid_c3%<>% ff_label(" ORCID ID  (If the collaborator do not have an ORCID account they should visit https://orcid.org/signin and click on Register now. Registration is quick and free.)")
data$p3_email_c3%<>% ff_label("  Email  ")
data$p3_fn_c4%<>% ff_label(" First name")
data$p3_ln_c4%<>% ff_label(" Last name (family name) ")
data$p3_orcid_c4%<>% ff_label(" ORCID ID  (If the collaborator do not have an ORCID account they should visit https://orcid.org/signin and click on Register now. Registration is quick and free.)")
data$p3_email_c4%<>% ff_label("  Email  ")
data$p3_fn_c5%<>% ff_label(" First name")
data$p3_ln_c5%<>% ff_label(" Last name (family name) ")
data$p3_orcid_c5%<>% ff_label(" ORCID ID  (If the collaborator do not have an ORCID account they should visit https://orcid.org/signin and click on Register now. Registration is quick and free.)")
data$p3_email_c5%<>% ff_label("  Email  ")
data$p4_miniteam_size%<>% ff_label(" How many collaborators would you like to register as part of this mini-team? ")
data$p4_fn_c1%<>% ff_label(" First name")
data$p4_ln_c1%<>% ff_label(" Last name (family name) ")
data$p4_orcid_c1%<>% ff_label(" ORCID ID  (If the collaborator do not have an ORCID account they should visit https://orcid.org/signin and click on Register now. Registration is quick and free.)")
data$p4_email_c1%<>% ff_label("  Email  ")
data$p4_fn_c2%<>% ff_label(" First name")
data$p4_ln_c2%<>% ff_label(" Last name (family name) ")
data$p4_orcid_c2%<>% ff_label(" ORCID ID  (If the collaborator do not have an ORCID account they should visit https://orcid.org/signin and click on Register now. Registration is quick and free.)")
data$p4_email_c2%<>% ff_label("  Email  ")
data$p4_fn_c3%<>% ff_label(" First name")
data$p4_ln_c3%<>% ff_label(" Last name (family name) ")
data$p4_orcid_c3%<>% ff_label(" ORCID ID  (If the collaborator do not have an ORCID account they should visit https://orcid.org/signin and click on Register now. Registration is quick and free.)")
data$p4_email_c3%<>% ff_label("  Email  ")
data$p4_fn_c4%<>% ff_label(" First name")
data$p4_ln_c4%<>% ff_label(" Last name (family name) ")
data$p4_orcid_c4%<>% ff_label(" ORCID ID  (If the collaborator do not have an ORCID account they should visit https://orcid.org/signin and click on Register now. Registration is quick and free.)")
data$p4_email_c4%<>% ff_label("  Email  ")
data$p4_fn_c5%<>% ff_label(" First name")
data$p4_ln_c5%<>% ff_label(" Last name (family name) ")
data$p4_orcid_c5%<>% ff_label(" ORCID ID  (If the collaborator do not have an ORCID account they should visit https://orcid.org/signin and click on Register now. Registration is quick and free.)")
data$p4_email_c5%<>% ff_label("  Email  ")
data$p5_miniteam_size%<>% ff_label(" How many collaborators would you like to register as part of this mini-team? ")
data$p5_fn_c1%<>% ff_label(" First name")
data$p5_ln_c1%<>% ff_label(" Last name (family name) ")
data$p5_orcid_c1%<>% ff_label(" ORCID ID  (If the collaborator do not have an ORCID account they should visit https://orcid.org/signin and click on Register now. Registration is quick and free.)")
data$p5_email_c1%<>% ff_label("  Email  ")
data$p5_fn_c2%<>% ff_label(" First name")
data$p5_ln_c2%<>% ff_label(" Last name (family name) ")
data$p5_orcid_c2%<>% ff_label(" ORCID ID  (If the collaborator do not have an ORCID account they should visit https://orcid.org/signin and click on Register now. Registration is quick and free.)")
data$p5_email_c2%<>% ff_label("  Email  ")
data$p5_fn_c3%<>% ff_label(" First name")
data$p5_ln_c3%<>% ff_label(" Last name (family name) ")
data$p5_orcid_c3%<>% ff_label(" ORCID ID  (If the collaborator do not have an ORCID account they should visit https://orcid.org/signin and click on Register now. Registration is quick and free.)")
data$p5_email_c3%<>% ff_label("  Email  ")
data$p5_fn_c4%<>% ff_label(" First name")
data$p5_ln_c4%<>% ff_label(" Last name (family name) ")
data$p5_orcid_c4%<>% ff_label(" ORCID ID  (If the collaborator do not have an ORCID account they should visit https://orcid.org/signin and click on Register now. Registration is quick and free.)")
data$p5_email_c4%<>% ff_label("  Email  ")
data$p5_fn_c5%<>% ff_label(" First name")
data$p5_ln_c5%<>% ff_label(" Last name (family name) ")
data$p5_orcid_c5%<>% ff_label(" ORCID ID  (If the collaborator do not have an ORCID account they should visit https://orcid.org/signin and click on Register now. Registration is quick and free.)")
data$p5_email_c5%<>% ff_label("  Email  ")
data$p6_miniteam_size%<>% ff_label(" How many collaborators would you like to register as part of this mini-team? ")
data$p6_fn_c1%<>% ff_label(" First name")
data$p6_ln_c1%<>% ff_label(" Last name (family name) ")
data$p6_orcid_c1%<>% ff_label(" ORCID ID  (If the collaborator do not have an ORCID account they should visit https://orcid.org/signin and click on Register now. Registration is quick and free.)")
data$p6_email_c1%<>% ff_label("  Email  ")
data$p6_fn_c2%<>% ff_label(" First name")
data$p6_ln_c2%<>% ff_label(" Last name (family name) ")
data$p6_orcid_c2%<>% ff_label(" ORCID ID  (If the collaborator do not have an ORCID account they should visit https://orcid.org/signin and click on Register now. Registration is quick and free.)")
data$p6_email_c2%<>% ff_label("  Email  ")
data$p6_fn_c3%<>% ff_label(" First name")
data$p6_ln_c3%<>% ff_label(" Last name (family name) ")
data$p6_orcid_c3%<>% ff_label(" ORCID ID  (If the collaborator do not have an ORCID account they should visit https://orcid.org/signin and click on Register now. Registration is quick and free.)")
data$p6_email_c3%<>% ff_label("  Email  ")
data$p6_fn_c4%<>% ff_label(" First name")
data$p6_ln_c4%<>% ff_label(" Last name (family name) ")
data$p6_orcid_c4%<>% ff_label(" ORCID ID  (If the collaborator do not have an ORCID account they should visit https://orcid.org/signin and click on Register now. Registration is quick and free.)")
data$p6_email_c4%<>% ff_label("  Email  ")
data$p6_fn_c5%<>% ff_label(" First name")
data$p6_ln_c5%<>% ff_label(" Last name (family name) ")
data$p6_orcid_c5%<>% ff_label(" ORCID ID  (If the collaborator do not have an ORCID account they should visit https://orcid.org/signin and click on Register now. Registration is quick and free.)")
data$p6_email_c5%<>% ff_label("  Email  ")
data$p7_miniteam_size%<>% ff_label(" How many collaborators would you like to register as part of this mini-team? ")
data$p7_fn_c1%<>% ff_label(" First name")
data$p7_ln_c1%<>% ff_label(" Last name (family name) ")
data$p7_orcid_c1%<>% ff_label(" ORCID ID  (If the collaborator do not have an ORCID account they should visit https://orcid.org/signin and click on Register now. Registration is quick and free.)")
data$p7_email_c1%<>% ff_label("  Email  ")
data$p7_fn_c2%<>% ff_label(" First name")
data$p7_ln_c2%<>% ff_label(" Last name (family name) ")
data$p7_orcid_c2%<>% ff_label(" ORCID ID  (If the collaborator do not have an ORCID account they should visit https://orcid.org/signin and click on Register now. Registration is quick and free.)")
data$p7_email_c2%<>% ff_label("  Email  ")
data$p7_fn_c3%<>% ff_label(" First name")
data$p7_ln_c3%<>% ff_label(" Last name (family name) ")
data$p7_orcid_c3%<>% ff_label(" ORCID ID  (If the collaborator do not have an ORCID account they should visit https://orcid.org/signin and click on Register now. Registration is quick and free.)")
data$p7_email_c3%<>% ff_label("  Email  ")
data$p7_fn_c4%<>% ff_label(" First name")
data$p7_ln_c4%<>% ff_label(" Last name (family name) ")
data$p7_orcid_c4%<>% ff_label(" ORCID ID  (If the collaborator do not have an ORCID account they should visit https://orcid.org/signin and click on Register now. Registration is quick and free.)")
data$p7_email_c4%<>% ff_label("  Email  ")
data$p7_fn_c5%<>% ff_label(" First name")
data$p7_ln_c5%<>% ff_label(" Last name (family name) ")
data$p7_orcid_c5%<>% ff_label(" ORCID ID  (If the collaborator do not have an ORCID account they should visit https://orcid.org/signin and click on Register now. Registration is quick and free.)")
data$p7_email_c5%<>% ff_label("  Email  ")
data$p8_miniteam_size%<>% ff_label(" How many collaborators would you like to register as part of this mini-team? ")
data$p8_fn_c1%<>% ff_label(" First name")
data$p8_ln_c1%<>% ff_label(" Last name (family name) ")
data$p8_orcid_c1%<>% ff_label(" ORCID ID  (If the collaborator do not have an ORCID account they should visit https://orcid.org/signin and click on Register now. Registration is quick and free.)")
data$p8_email_c1%<>% ff_label("  Email  ")
data$p8_fn_c2%<>% ff_label(" First name")
data$p8_ln_c2%<>% ff_label(" Last name (family name) ")
data$p8_orcid_c2%<>% ff_label(" ORCID ID  (If the collaborator do not have an ORCID account they should visit https://orcid.org/signin and click on Register now. Registration is quick and free.)")
data$p8_email_c2%<>% ff_label("  Email  ")
data$p8_fn_c3%<>% ff_label(" First name")
data$p8_ln_c3%<>% ff_label(" Last name (family name) ")
data$p8_orcid_c3%<>% ff_label(" ORCID ID  (If the collaborator do not have an ORCID account they should visit https://orcid.org/signin and click on Register now. Registration is quick and free.)")
data$p8_email_c3%<>% ff_label("  Email  ")
data$p8_fn_c4%<>% ff_label(" First name")
data$p8_ln_c4%<>% ff_label(" Last name (family name) ")
data$p8_orcid_c4%<>% ff_label(" ORCID ID  (If the collaborator do not have an ORCID account they should visit https://orcid.org/signin and click on Register now. Registration is quick and free.)")
data$p8_email_c4%<>% ff_label("  Email  ")
data$p8_fn_c5%<>% ff_label(" First name")
data$p8_ln_c5%<>% ff_label(" Last name (family name) ")
data$p8_orcid_c5%<>% ff_label(" ORCID ID  (If the collaborator do not have an ORCID account they should visit https://orcid.org/signin and click on Register now. Registration is quick and free.)")
data$p8_email_c5%<>% ff_label("  Email  ")
data$val_fn%<>% ff_label(" First name")
data$val_ln%<>% ff_label(" Last name (family name) ")
data$val_orcid%<>% ff_label(" ORCID ID  (If the collaborator do not have an ORCID account they should visit https://orcid.org/signin and click on Register now. Registration is quick and free.)")
data$val_email%<>% ff_label("  Email  ")
data$miniteam_application_portal_complete%<>% ff_label("Complete?")
data$hosp_type%<>% ff_label(" Hospital type  (Please select the option which best describes your hospital.)")
data$hosp_fund%<>% ff_label(" Hospital funding")
data$hosp_bed%<>% ff_label(" Total number of inpatient beds  (Please include both surgical and non-surgical beds.)")
data$hosp_itu_yn%<>% ff_label(" Do you have Level 2 (HDU) or Level 3 (ITU) facilities at your hospital?")
data$hosp_itu_bed%<>% ff_label(" Total number of Level 2 (HDU) or Level 3 (ITU) beds")
data$hosp_hpb%<>% ff_label(" Do you have a specialised HPB team at your hospital?")
data$hosp_hpb_oncall%<>% ff_label(" Are there on-call services from the specialised HPB team?")
data$hosp_hpb_path%<>% ff_label(" Does the specialised HPB team have a dedicated pathway for management of bile duct injury?")
data$hosp_hpb_region%<>% ff_label(" Are there on-call surgeons specialised in HPB?")
data$hosp_mis_yn%<>% ff_label(" Do you have access to minimally invasive surgical equipment?")
data$hosp_mis_type___1%<>% ff_label(" Type of minimally invasive surgical equipment available (choice=Laparoscopic)")
data$hosp_mis_type___2%<>% ff_label(" Type of minimally invasive surgical equipment available (choice=Robotic)")
data$hosp_mis_image%<>% ff_label(" Do you routinely take intraoperative images at your hospital?")
data$service_chole_n%<>% ff_label(" What is the approximate total number of cholecystectomies performed each year at your hospital?")
data$service_cons_n%<>% ff_label(" What is the number of consultant/attending surgeons who perform cholecystectomies each year at your hospital?")
data$service_cons_lap_n%<>% ff_label(" What is the number of consultant/attending surgeons who perform laparoscopic cholecystectomy at your hospital?")
data$service_cons_type___1%<>% ff_label(" Which specialist consultant/attending surgeons perform cholecystectomies at your hospital? (choice=General)")
data$service_cons_type___2%<>% ff_label(" Which specialist consultant/attending surgeons perform cholecystectomies at your hospital? (choice=Upper GI)")
data$service_cons_type___3%<>% ff_label(" Which specialist consultant/attending surgeons perform cholecystectomies at your hospital? (choice=HPB)")
data$service_cons_type___4%<>% ff_label(" Which specialist consultant/attending surgeons perform cholecystectomies at your hospital? (choice=Colorectal)")
data$service_cons_type___5%<>% ff_label(" Which specialist consultant/attending surgeons perform cholecystectomies at your hospital? (choice=Breast)")
data$service_cons_type___6%<>% ff_label(" Which specialist consultant/attending surgeons perform cholecystectomies at your hospital? (choice=Other)")
data$service_type___1%<>% ff_label(" What type of services for cholecystectomy services is provided at your hospital? (choice=Elective)")
data$service_type___2%<>% ff_label(" What type of services for cholecystectomy services is provided at your hospital? (choice=Emergency)")
data$service_eme_n%<>% ff_label(" What is the approximate total number of emergency cholecystectomies performed each year at your hospital?")
data$service_eme_theatre%<>% ff_label(" Do you have dedicated theatres for these emergency services?")
data$service_setting___1%<>% ff_label(" Where are cholecystectomies performed at your hospital?   (choice=Day unit)")
data$service_setting___2%<>% ff_label(" Where are cholecystectomies performed at your hospital?   (choice=Elective theatre)")
data$service_setting___3%<>% ff_label(" Where are cholecystectomies performed at your hospital?   (choice=Emergency theatre)")
data$service_fu%<>% ff_label(" Do you follow-up after cholecystectomy?")
data$diag_us_yn%<>% ff_label(" Ultrasound")
data$diag_ct_yn%<>% ff_label(" Computerised Tomography (CT)")
data$diag_mrcp_yn%<>% ff_label(" Magnetic Resonance Cholangiopancreatography (MRCP)")
data$diag_eus_yn%<>% ff_label(" Endoscopic Ultrasound (EUS)")
data$diag_hida_yn%<>% ff_label(" Hepatobiliary Iminodiacetic Acid (HIDA)")
data$diag_ostomy_yn%<>% ff_label(" Does your hospital have access to cholecystostomy for gallbladder drainage?")
data$diag_ostomy_oncall%<>% ff_label(" Are there on-call services for cholecystostomy at your hospital?")
data$diag_ostomy_region%<>% ff_label(" Are there on-call interventional radiologists who perform cholecystostomy available?")
data$diag_ercp%<>% ff_label(" Is there a dedicated Endoscopic retrograde cholangiopancreatography (ERCP) list at your hospital?")
data$diag_ioc%<>% ff_label(" Intraoperative Cholangiogram (IOC)")
data$diag_lu%<>% ff_label(" Laparoscopic Ultrasound")
data$diag_icg%<>% ff_label(" Incisionless fluorescent cholangiography")
data$diag_hist%<>% ff_label(" Do you send gallbladders for histological examination after surgery?")
data$train_perform%<>% ff_label(" Are there trainees in the department who perform gallbladder surgery?")
data$train_n%<>% ff_label(" How many trainees are there in the department who perform gallbladder surgery?")
data$train_grade___1%<>% ff_label(" What are the trainees grades who perform gallbladder surgery in your department? (choice=Post-training fellow)")
data$train_grade___2%<>% ff_label(" What are the trainees grades who perform gallbladder surgery in your department? (choice=Senior trainee)")
data$train_grade___3%<>% ff_label(" What are the trainees grades who perform gallbladder surgery in your department? (choice=Junior trainee)")
data$train_grade___4%<>% ff_label(" What are the trainees grades who perform gallbladder surgery in your department? (choice=Non-trainees or doctors)")
data$train_sim_yn___1%<>% ff_label(" Are there facilities for simulations training for cholecystectomies? (choice=Yes (Local hospital))")
data$train_sim_yn___2%<>% ff_label(" Are there facilities for simulations training for cholecystectomies? (choice=Yes (Regional))")
data$train_sim_yn___3%<>% ff_label(" Are there facilities for simulations training for cholecystectomies? (choice=Yes (National))")
data$train_sim_yn___4%<>% ff_label(" Are there facilities for simulations training for cholecystectomies? (choice=No)")
data$train_sim_type___1%<>% ff_label(" What are the types of simulation training available? (choice=Box trainer)")
data$train_sim_type___2%<>% ff_label(" What are the types of simulation training available? (choice=IT simulation model)")
data$train_sim_type___3%<>% ff_label(" What are the types of simulation training available? (choice=Animal model)")
data$tain_chole___1%<>% ff_label(" Are there structured educational programmes or coaching for cholecystectomy training? (choice=Yes (Local hospital))")
data$tain_chole___2%<>% ff_label(" Are there structured educational programmes or coaching for cholecystectomy training? (choice=Yes (Regional))")
data$tain_chole___3%<>% ff_label(" Are there structured educational programmes or coaching for cholecystectomy training? (choice=Yes (National))")
data$tain_chole___4%<>% ff_label(" Are there structured educational programmes or coaching for cholecystectomy training? (choice=No)")
data$train_bdi___1%<>% ff_label(" Are there specific structured educational programmes or coaching for bile duct injury training? (choice=Yes (Local hospital))")
data$train_bdi___2%<>% ff_label(" Are there specific structured educational programmes or coaching for bile duct injury training? (choice=Yes (Regional))")
data$train_bdi___3%<>% ff_label(" Are there specific structured educational programmes or coaching for bile duct injury training? (choice=Yes (National))")
data$train_bdi___4%<>% ff_label(" Are there specific structured educational programmes or coaching for bile duct injury training? (choice=No)")
data$green_lap%<>% ff_label(" Are reusable laparoscopic ports used?")
data$green_surginst%<>% ff_label(" Are reusable surgical instruments used?")
data$green_drape%<>% ff_label(" Are reusable drapes used?")
data$green_gown%<>% ff_label(" Are reusable gowns used?")
data$green_scrubcap%<>% ff_label(" Are reusable scrub caps used?")
data$green_recycle%<>% ff_label(" Are single-use instruments recycled?")
data$green_recycle_waste%<>% ff_label(" Are clean paper and plastic waste recycled?")
data$green_ga%<>% ff_label(" Is general anaesthesia given through IV rather than anaesthetic gases for environmental reasons?")
data$site_survey_complete%<>% ff_label("Complete?")
data$data_collection_dag%<>% ff_label("Data dag:")
data$admin_complete%<>% ff_label("Complete?")